/**
 * Cosmic Explorer - Planet Data Store
 * 
 * Complete data for all 8 planets in the solar system.
 * Used by the gallery, detail, comparison, and quiz pages.
 */

const PLANETS = [
    {
        name: "Mercury",
        slug: "mercury",
        type: "Terrestrial",
        tagline: "The Swift Messenger",
        color: "#8c8c8c",
        image: "assets/images/mercury.png",
        position: 1,
        diameter: 4879,         // km
        mass: 0.055,            // relative to Earth
        distanceFromSun: 57.9,  // million km
        orbitalPeriod: 88,      // days
        rotationPeriod: 58.6,   // days
        moons: 0,
        temperature: { min: -180, max: 430 },  // °C
        gravity: 3.7,           // m/s²
        atmosphere: "Minimal — traces of oxygen, sodium, hydrogen",
        description: "Mercury is the smallest planet in our solar system and the closest to the Sun. Despite being so close to the Sun, Mercury is not the hottest planet — that title belongs to Venus. Mercury has virtually no atmosphere to retain heat, leading to extreme temperature swings between its scorching days and freezing nights.",
        funFacts: [
            "A year on Mercury lasts just 88 Earth days",
            "Mercury has no moons and no rings",
            "It has a massive iron core that takes up about 75% of the planet's radius",
            "Mercury's surface resembles our Moon with many craters",
            "Despite being closest to the Sun, it's NOT the hottest planet"
        ]
    },
    {
        name: "Venus",
        slug: "venus",
        type: "Terrestrial",
        tagline: "Earth's Toxic Twin",
        color: "#e6c67a",
        image: "assets/images/venus.png",
        position: 2,
        diameter: 12104,
        mass: 0.815,
        distanceFromSun: 108.2,
        orbitalPeriod: 225,
        rotationPeriod: 243,
        moons: 0,
        temperature: { min: 462, max: 462 },
        gravity: 8.87,
        atmosphere: "Dense — 96% carbon dioxide, sulfuric acid clouds",
        description: "Venus is often called Earth's 'sister planet' because of their similar size, but the resemblance ends there. Venus has a thick, toxic atmosphere filled with carbon dioxide and clouds of sulfuric acid. Its extreme greenhouse effect makes it the hottest planet in our solar system, even hotter than Mercury.",
        funFacts: [
            "Venus rotates backwards compared to most planets (retrograde rotation)",
            "A day on Venus is longer than its year",
            "Surface pressure on Venus is 90 times that of Earth",
            "Venus is the brightest natural object in the night sky after the Moon",
            "It rains sulfuric acid on Venus, but it evaporates before reaching the ground"
        ]
    },
    {
        name: "Earth",
        slug: "earth",
        type: "Terrestrial",
        tagline: "Our Pale Blue Dot",
        color: "#4fa3e0",
        image: "assets/images/earth.png",
        position: 3,
        diameter: 12742,
        mass: 1.0,
        distanceFromSun: 149.6,
        orbitalPeriod: 365.25,
        rotationPeriod: 1,
        moons: 1,
        temperature: { min: -89, max: 57 },
        gravity: 9.81,
        atmosphere: "78% nitrogen, 21% oxygen, 1% other gases",
        description: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is covered with water, mostly by oceans. Earth's atmosphere protects life by absorbing ultraviolet solar radiation, warming the surface through heat retention, and reducing temperature extremes between day and night.",
        funFacts: [
            "Earth is the only planet not named after a Greek or Roman god",
            "Earth's rotation is gradually slowing — days are getting longer",
            "The deepest point on Earth (Mariana Trench) is 11,034 meters deep",
            "Earth has a powerful magnetic field generated by its nickel-iron core",
            "70% of Earth's surface is water, but only 3% is fresh water"
        ]
    },
    {
        name: "Mars",
        slug: "mars",
        type: "Terrestrial",
        tagline: "The Red Planet",
        color: "#d45a36",
        image: "assets/images/mars.png",
        position: 4,
        diameter: 6779,
        mass: 0.107,
        distanceFromSun: 227.9,
        orbitalPeriod: 687,
        rotationPeriod: 1.03,
        moons: 2,
        temperature: { min: -140, max: 20 },
        gravity: 3.72,
        atmosphere: "Thin — 95% carbon dioxide, 3% nitrogen",
        description: "Mars is the fourth planet from the Sun and the second-smallest planet in our solar system. Known as the 'Red Planet' due to iron oxide (rust) on its surface, Mars has been a target for exploration with numerous rovers and spacecraft. It has the tallest mountain (Olympus Mons) and the deepest canyon (Valles Marineris) in the solar system.",
        funFacts: [
            "Mars has the tallest volcano in the solar system — Olympus Mons (21.9 km high)",
            "Mars has two small moons named Phobos and Deimos",
            "A day on Mars (called a 'sol') is about 37 minutes longer than an Earth day",
            "Mars has seasons like Earth because of its tilted axis",
            "NASA's Perseverance rover is currently exploring Mars' Jezero Crater"
        ]
    },
    {
        name: "Jupiter",
        slug: "jupiter",
        type: "Gas Giant",
        tagline: "The King of Planets",
        color: "#c89b6b",
        image: "assets/images/jupiter.png",
        position: 5,
        diameter: 139820,
        mass: 317.8,
        distanceFromSun: 778.5,
        orbitalPeriod: 4333,
        rotationPeriod: 0.41,
        moons: 95,
        temperature: { min: -145, max: -108 },
        gravity: 24.79,
        atmosphere: "90% hydrogen, 10% helium, traces of methane and ammonia",
        description: "Jupiter is the largest planet in our solar system — so large that all other planets could fit inside it. This gas giant is made mostly of hydrogen and helium, similar to the Sun. Its most famous feature is the Great Red Spot, a giant storm that has been raging for at least 350 years and is larger than Earth.",
        funFacts: [
            "Jupiter has the shortest day of all planets — just 10 hours",
            "The Great Red Spot is a storm larger than Earth that's lasted 350+ years",
            "Jupiter has at least 95 known moons, including the four large Galilean moons",
            "Jupiter's magnetic field is 20,000 times stronger than Earth's",
            "Jupiter acts as a 'cosmic vacuum cleaner,' deflecting asteroids from hitting Earth"
        ]
    },
    {
        name: "Saturn",
        slug: "saturn",
        type: "Gas Giant",
        tagline: "The Ringed Beauty",
        color: "#e4c76e",
        image: "assets/images/saturn.png",
        position: 6,
        diameter: 116460,
        mass: 95.2,
        distanceFromSun: 1434,
        orbitalPeriod: 10759,
        rotationPeriod: 0.45,
        moons: 146,
        temperature: { min: -178, max: -139 },
        gravity: 10.44,
        atmosphere: "96% hydrogen, 3% helium, traces of methane and ammonia",
        description: "Saturn is the sixth planet from the Sun and the second-largest in our solar system. It's best known for its stunning ring system, which is made mostly of ice particles, rocky debris, and dust. Saturn is so light that it would actually float if you could find a body of water big enough — it's less dense than water.",
        funFacts: [
            "Saturn's rings span up to 282,000 km but are only about 10 meters thick",
            "Saturn could float in water — it's the only planet less dense than water",
            "Saturn has 146 known moons, including Titan which has its own atmosphere",
            "Winds on Saturn can reach speeds of 1,800 km/h",
            "Saturn's moon Enceladus shoots geysers of water into space"
        ]
    },
    {
        name: "Uranus",
        slug: "uranus",
        type: "Ice Giant",
        tagline: "The Tilted World",
        color: "#73d5e8",
        image: null,
        position: 7,
        diameter: 50724,
        mass: 14.5,
        distanceFromSun: 2871,
        orbitalPeriod: 30687,
        rotationPeriod: 0.72,
        moons: 28,
        temperature: { min: -224, max: -197 },
        gravity: 8.87,
        atmosphere: "83% hydrogen, 15% helium, 2% methane (gives blue-green color)",
        description: "Uranus is the seventh planet from the Sun and the third-largest in our solar system. What makes it unique is its extreme axial tilt of 98 degrees — it essentially orbits the Sun on its side. The methane in its atmosphere gives it a beautiful blue-green color. Uranus is classified as an 'ice giant' rather than a gas giant.",
        funFacts: [
            "Uranus rotates on its side with an axial tilt of 98 degrees",
            "It was the first planet discovered with a telescope (by William Herschel in 1781)",
            "Uranus has 13 known rings, though they are faint",
            "A year on Uranus lasts 84 Earth years",
            "Uranus is the coldest planet in the solar system despite not being the farthest"
        ]
    },
    {
        name: "Neptune",
        slug: "neptune",
        type: "Ice Giant",
        tagline: "The Windiest World",
        color: "#3f6ccc",
        image: null,
        position: 8,
        diameter: 49244,
        mass: 17.1,
        distanceFromSun: 4495,
        orbitalPeriod: 60190,
        rotationPeriod: 0.67,
        moons: 16,
        temperature: { min: -218, max: -200 },
        gravity: 11.15,
        atmosphere: "80% hydrogen, 19% helium, 1% methane",
        description: "Neptune is the eighth and farthest planet from the Sun. This deep blue ice giant was the first planet located through mathematical predictions rather than direct observation. Neptune has the strongest winds of any planet in the solar system, with speeds reaching 2,100 km/h. Its vivid blue color comes from methane in the atmosphere.",
        funFacts: [
            "Neptune was discovered through mathematics before it was ever seen",
            "Winds on Neptune can exceed 2,100 km/h — the fastest in the solar system",
            "Neptune has completed only one orbit since its discovery in 1846",
            "Its largest moon, Triton, orbits in the opposite direction to Neptune's rotation",
            "Neptune has 6 rings, though they are very faint"
        ]
    }
];

/**
 * Quiz questions about the solar system
 */
const QUIZ_QUESTIONS = [
    {
        question: "Which planet is the largest in our solar system?",
        options: ["Saturn", "Jupiter", "Neptune", "Uranus"],
        correct: 1
    },
    {
        question: "Which planet is known as the 'Red Planet'?",
        options: ["Venus", "Mercury", "Mars", "Jupiter"],
        correct: 2
    },
    {
        question: "How many moons does Earth have?",
        options: ["0", "1", "2", "3"],
        correct: 1
    },
    {
        question: "Which planet has the most prominent ring system?",
        options: ["Jupiter", "Uranus", "Neptune", "Saturn"],
        correct: 3
    },
    {
        question: "What is the hottest planet in our solar system?",
        options: ["Mercury", "Venus", "Mars", "Jupiter"],
        correct: 1
    },
    {
        question: "Which planet rotates on its side with a 98-degree tilt?",
        options: ["Neptune", "Saturn", "Uranus", "Pluto"],
        correct: 2
    },
    {
        question: "What percentage of Earth's surface is covered by water?",
        options: ["50%", "60%", "71%", "80%"],
        correct: 2
    },
    {
        question: "Which planet has the strongest winds in the solar system?",
        options: ["Jupiter", "Saturn", "Uranus", "Neptune"],
        correct: 3
    },
    {
        question: "Which is the smallest planet in our solar system?",
        options: ["Mars", "Mercury", "Venus", "Earth"],
        correct: 1
    },
    {
        question: "How long does it take light from the Sun to reach Earth?",
        options: ["4 minutes", "8 minutes", "12 minutes", "16 minutes"],
        correct: 1
    }
];

/**
 * Helper function to get planet by slug
 */
function getPlanetBySlug(slug) {
    return PLANETS.find(p => p.slug === slug.toLowerCase());
}

/**
 * Helper function to format large numbers
 */
function formatNumber(num) {
    return num.toLocaleString();
}
